site_name: P[y]TAB

site_author: Massimo Santini

copyright: "&copy; Massimo Santini, 2026"

theme:
  name: material
  palette:
    primary: 'blue grey'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu mono'
  language: 'it'
  use_directory_urls: true

repo_name: 'mapio/pytab-2026'
repo_url: 'https://github.com/mapio/pytab-2026'
edit_uri: ''

extra:
  search:
    language: 'it'
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/mapio
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/mapio
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/massimosantini/
    
